name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# give the workflow explicit permissions so deploy action can run
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Show dist contents (debug)
        run: |
          echo "=== pwd ==="
          pwd
          echo "=== node version ==="
          node -v || true
          echo "=== npm version ==="
          npm -v || true
          echo "=== ls -la workspace ==="
          ls -la
          echo "=== ls -la dist ==="
          ls -la dist || true
          echo "=== find dist ==="
          find dist -maxdepth 3 -type f -print || true

      - name: Upload artifact for pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
